# Generated by Django 4.1.5 on 2023-03-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SrNo', models.CharField(max_length=122)),
                ('name', models.CharField(max_length=122)),
                ('Email', models.CharField(max_length=122)),
                ('PhoneNumber', models.CharField(max_length=12)),
                ('Countryname', models.CharField(max_length=5)),
                ('DESC', models.TextField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
    ]
