# Generated by Django 4.1.5 on 2023-03-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tmapps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SrNo', models.CharField(max_length=122)),
                ('name', models.CharField(max_length=122)),
                ('Email', models.CharField(max_length=122)),
                ('PhoneNumber', models.CharField(max_length=12)),
                ('Countryname', models.CharField(max_length=12)),
                ('DESC', models.TextField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Cotact',
        ),
    ]
