# Generated by Django 4.1.5 on 2023-03-21 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tmapps', '0002_contact_delete_cotact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='SrNo',
        ),
    ]
