# Generated by Django 4.1.5 on 2023-03-21 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tmapps', '0003_remove_contact_srno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='Name',
        ),
    ]
