# Generated by Django 4.1.5 on 2023-03-21 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tmapps', '0004_rename_name_contact_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='DESC',
            new_name='DISC',
        ),
    ]
