# Generated by Django 4.1.5 on 2023-03-21 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tmapps', '0005_rename_desc_contact_disc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Name',
            new_name='name',
        ),
    ]
