# Generated by Django 4.1.5 on 2023-03-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tmapps', '0006_rename_name_contact_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='DISC',
            new_name='DESC',
        ),
        migrations.AddField(
            model_name='contact',
            name='SrNo',
            field=models.CharField(default='exit', max_length=122),
            preserve_default=False,
        ),
    ]
