# Generated by Django 4.1.5 on 2023-03-21 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tmapps', '0007_rename_disc_contact_desc_contact_srno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='DESC',
            new_name='DISC',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='SrNo',
        ),
    ]
