# Generated by Django 4.1.5 on 2023-03-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tmapps', '0008_rename_desc_contact_disc_remove_contact_srno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Countryname',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='DISC',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='PhoneNumber',
        ),
        migrations.AddField(
            model_name='contact',
            name='desc',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
    ]
